version: '3.8'

services:
    auto_contact:
        container_name: auto_contact
        build: .
        restart: always
        environment:
            DISPLAY: :99
            XDG_RUNTIME_DIR: /tmp/runtime-root
        env_file:
            - .env.dev
        volumes:
            - .:/app
        ports:
            - "5002:5000"
        networks:
            - auto_contact_net
    app_mysql:
        container_name: app_mysql_auto_contact
        image: "mysql/mysql-server:8.0"
        ports:
            - "3307:3306"
        env_file:
            - .env.dev
        environment:
            MYSQL_ROOT_PASSWORD: 59j0PUyA7lD4
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: auto_db
            MYSQL_USER: auto_db_user
            MYSQL_PASSWORD: 59j0PUyA7lD4
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - auto_contact_net
    # add service rabbitmq
    
    rabbitmq:
        container_name: rabbitmq_auto_contact
        image: rabbitmq:3-management
        restart: always
        env_file:
            - .env.dev
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: Fammqpassword@2024
        networks:
            - auto_contact_net
networks:
  auto_contact_net:
    driver: bridge
    
